# Generated by Django 5.2.4 on 2026-08-27 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_add_employee_roles_and_collected_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("endpoint", models.CharField(max_length=500)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_snapshot", models.JSONField(blank=True, default=dict)),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_keys",
                        to="tenancy.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["key", "endpoint"], name="common_idem_key_74d70d_idx"
                    ),
                    models.Index(
                        fields=["merchant", "key"],
                        name="common_idem_merchan_bab83c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "endpoint"), name="uniq_idempotency_key_endpoint"
                    )
                ],
            },
        ),
    ]
