# Generated by Django 5.2.4 on 2026-09-04 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_add_cancel_reason"),
        ("tenancy", "0004_add_merchant_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("EMPLOYEE", "Empleado"), ("CUSTOMER", "Cliente")],
                        max_length=20,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("message", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NEW_ORDER", "Nuevo pedido"),
                            ("ORDER_STATE_CHANGE", "Cambio de estado"),
                            ("PAYMENT_PENDING", "Pago pendiente"),
                            ("PAYMENT_CONFIRMED", "Pago confirmado"),
                            ("SYSTEM", "Sistema"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tenancy.merchant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "is_read"],
                        name="notificatio_merchan_d8f809_idx",
                    ),
                    models.Index(
                        fields=["merchant", "recipient_type"],
                        name="notificatio_merchan_6a39f2_idx",
                    ),
                ],
            },
        ),
    ]
