# Generated by Django 5.2.4 on 2026-08-27 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("weekday", models.SmallIntegerField()),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="tenancy.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                ("is_closed", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_dates",
                        to="tenancy.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_ranges",
                        to="tenancy.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["opens_at"],
            },
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["merchant", "weekday"], name="tenancy_sch_merchan_21ce91_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("merchant", "weekday"),
                name="uniq_schedule_per_merchant_weekday",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="schedule_weekday_0_6",
            ),
        ),
        migrations.AddIndex(
            model_name="specialdate",
            index=models.Index(
                fields=["merchant", "date"], name="tenancy_spe_merchan_b01321_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="specialdate",
            constraint=models.UniqueConstraint(
                fields=("merchant", "date"), name="uniq_special_date_per_merchant"
            ),
        ),
        migrations.AddIndex(
            model_name="timerange",
            index=models.Index(
                fields=["schedule", "opens_at"], name="tenancy_tim_schedul_53e5db_idx"
            ),
        ),
    ]
