# Generated by Django 5.2.4 on 2026-08-27 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_schedule_specialdate_timerange_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("display_name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="tenancy.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("CAJERO", "Cajero"),
                            ("PREPARADOR", "Preparador"),
                            ("REPARTIDOR", "Repartidor"),
                            ("TOMA_PEDIDOS", "Toma Pedidos"),
                        ],
                        max_length=13,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_roles",
                        to="tenancy.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["role"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["merchant", "is_active"], name="tenancy_emp_merchan_a15838_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["merchant", "display_name"],
                name="tenancy_emp_merchan_c2e1e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeerole",
            index=models.Index(
                fields=["employee", "role"], name="tenancy_emp_employe_4ff7fb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeerole",
            constraint=models.UniqueConstraint(
                fields=("employee", "role"), name="uniq_employee_role"
            ),
        ),
    ]
