# Generated by Django 5.2.4 on 2026-09-08 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0004_add_merchant_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=120)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlatformUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("role", models.CharField(max_length=20)),
                (
                    "kind",
                    models.CharField(
                        choices=[("PERSONAL", "Personal"), ("STATION", "Station")],
                        default="PERSONAL",
                        max_length=10,
                    ),
                ),
                ("must_change_password", models.BooleanField(default=True)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["fullname"]},
        ),
        migrations.RemoveIndex(
            model_name="employee",
            name="tenancy_emp_merchan_c2e1e3_idx",
        ),
        # Columns already exist in dev DB (added out-of-band in a prior
        # session); sync state only so future autodetector stays clean.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="employee",
                    name="address",
                    field=models.CharField(blank=True, max_length=200),
                ),
                migrations.AddField(
                    model_name="employee",
                    name="city",
                    field=models.CharField(blank=True, max_length=100),
                ),
                migrations.AddField(
                    model_name="employee",
                    name="cuil",
                    field=models.CharField(max_length=13),
                ),
                migrations.AddField(
                    model_name="employee",
                    name="fullname",
                    field=models.CharField(max_length=120),
                ),
                migrations.AlterField(
                    model_name="employee",
                    name="display_name",
                    field=models.CharField(blank=True, max_length=120),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name="merchant",
            name="has_branches",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="merchant",
            name="seat_limit",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["merchant", "fullname"], name="tenancy_emp_merchan_d3a879_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("merchant", "cuil"), name="unique_employee_cuil_per_merchant"
            ),
        ),
        migrations.AddField(
            model_name="auditentry",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditentry",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_entries",
                to="tenancy.merchant",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="tenancy.merchant",
            ),
        ),
        migrations.AddField(
            model_name="platformuser",
            name="assigned_merchants",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_staff", to="tenancy.merchant"
            ),
        ),
        migrations.AddField(
            model_name="platformuser",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platform_users",
                to="tenancy.branch",
            ),
        ),
        migrations.AddField(
            model_name="platformuser",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platform_users",
                to="tenancy.merchant",
            ),
        ),
        migrations.AddField(
            model_name="platformuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platform_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditentry",
            index=models.Index(
                fields=["merchant", "created_at"], name="tenancy_aud_merchan_cd186f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["merchant", "is_active"], name="tenancy_bra_merchan_3d7db5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("merchant", "name"), name="unique_branch_name_per_merchant"
            ),
        ),
        migrations.AddIndex(
            model_name="platformuser",
            index=models.Index(
                fields=["merchant", "role"], name="tenancy_pla_merchan_0d312b_idx"
            ),
        ),
    ]
