# Generated by Django 5.2.4 on 2026-09-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0005_auditentry_branch_platformuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformuser",
            name="sector",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
