# Generated by Django 5.2.4 on 2026-08-27 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("tenancy", "0002_schedule_specialdate_timerange_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.PositiveIntegerField()),
                ("customer_name", models.CharField(max_length=120)),
                ("customer_phone", models.CharField(blank=True, max_length=40)),
                (
                    "fulfillment",
                    models.CharField(
                        choices=[("DELIVERY", "Delivery"), ("PICKUP", "Pickup")],
                        max_length=8,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RECIBIDO", "Recibido"),
                            ("PREPARACION", "Preparacion"),
                            ("FACTURACION", "Facturacion"),
                            ("LOGISTICA", "Logistica"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="RECIBIDO",
                        max_length=12,
                    ),
                ),
                ("business_date", models.DateField()),
                ("address", models.TextField(blank=True)),
                (
                    "items_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("cash_declared", models.BooleanField(default=False)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="tenancy.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date", "-code"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=160)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("flavors", models.JSONField(blank=True, default=list)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["merchant", "state", "business_date"],
                name="orders_orde_merchan_8ee550_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("merchant", "business_date", "code"),
                name="uniq_order_code_per_merchant_day",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="orders_orde_order_i_5d347b_idx"),
        ),
    ]
