# Generated by Django 5.2.4 on 2026-08-27 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_add_employee_roles_and_collected_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=80)),
                ("entity_id", models.BigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("SOFT_DELETE", "Soft Delete"),
                            ("STATE_TRANSITION", "State Transition"),
                            ("PAYMENT", "Payment"),
                            ("CASH_MOVEMENT", "Cash Movement"),
                            ("CLOSURE", "Closure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="tenancy.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "entity", "entity_id"],
                        name="audit_audit_merchan_c18100_idx",
                    ),
                    models.Index(
                        fields=["merchant", "created_at"],
                        name="audit_audit_merchan_bb4e4f_idx",
                    ),
                ],
            },
        ),
    ]
