# Generated by Django 5.2.17 on 2026-08-25 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="tenancy.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flavors",
                        to="catalog.category",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flavors",
                        to="tenancy.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("POTE", "Pote"), ("UNIT", "Unit")], max_length=4
                    ),
                ),
                (
                    "pote_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KG_1", "1kg"),
                            ("KG_HALF", "1/2kg"),
                            ("KG_QUARTER", "1/4kg"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("min_flavors", models.SmallIntegerField(blank=True, null=True)),
                ("max_flavors", models.SmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="tenancy.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFlavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flavor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_products",
                        to="catalog.flavor",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.merchant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_flavors",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["merchant", "is_active", "position"],
                name="catalog_cat_merchan_d4424b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("merchant", "name"), name="uniq_category_name_per_merchant"
            ),
        ),
        migrations.AddConstraint(
            model_name="flavor",
            constraint=models.UniqueConstraint(
                fields=("merchant", "name"), name="uniq_flavor_name_per_merchant"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["merchant", "category", "is_active"],
                name="catalog_pro_merchan_cb9c1f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product_type", "UNIT"),
                    models.Q(
                        ("pote_size__isnull", False),
                        ("min_flavors__isnull", False),
                        ("max_flavors__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="pote_requires_size_and_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product_type", "POTE"),
                    models.Q(
                        ("pote_size__isnull", True),
                        ("min_flavors__isnull", True),
                        ("max_flavors__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="unit_has_no_pote_fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="productflavor",
            constraint=models.UniqueConstraint(
                fields=("product", "flavor"), name="uniq_product_flavor"
            ),
        ),
    ]
