# Generated by Django 5.2.4 on 2026-08-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("tenancy", "0003_add_employee_roles_and_collected_by"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="pote_requires_size_and_bounds",
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="unit_has_no_pote_fields",
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product_type", "POTE"),
                    ("pote_size__isnull", True),
                    _connector="OR",
                ),
                name="unit_has_no_pote_size",
            ),
        ),
    ]
