# Generated by Django 5.2.4 on 2026-09-02 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_image"),
        ("tenancy", "0004_add_merchant_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("visit_count", models.PositiveIntegerField(default=0)),
                ("buyer_count", models.PositiveIntegerField(default=0)),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_stat",
                        to="tenancy.merchant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catálogo stat",
                "verbose_name_plural": "Catálogos stat",
            },
        ),
    ]
