# Generated by Django 5.2.4 on 2026-08-27 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0002_schedule_specialdate_timerange_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "modo",
                    models.CharField(
                        choices=[("PROPIO", "Propio"), ("TERCERIZADO", "Tercerizado")],
                        default="PROPIO",
                        max_length=12,
                    ),
                ),
                (
                    "cobro",
                    models.CharField(
                        choices=[
                            ("EN_PEDIDO", "En pedido"),
                            ("EN_ENTREGA", "En entrega"),
                        ],
                        default="EN_PEDIDO",
                        max_length=10,
                    ),
                ),
                (
                    "calculo",
                    models.CharField(
                        choices=[
                            ("POR_ZONA", "Por zona"),
                            ("FIJO", "Fijo"),
                            ("GRATIS_MONTO", "Gratis sobre monto"),
                            ("POR_DISTANCIA", "Por distancia"),
                        ],
                        default="FIJO",
                        max_length=13,
                    ),
                ),
                (
                    "flat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "free_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "third_party_fixed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_config",
                        to="tenancy.merchant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["merchant"], name="delivery_de_merchan_7f16a3_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("base_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="tenancy.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "name"],
                        name="delivery_zo_merchan_1f5170_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("merchant", "name"), name="uniq_zone_name_per_merchant"
                    )
                ],
            },
        ),
    ]
