# Generated by Django 5.2.4 on 2026-08-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryconfig",
            name="cobro",
            field=models.CharField(
                choices=[
                    ("EN_PEDIDO", "En pedido"),
                    ("EN_ENTREGA", "En entrega"),
                    ("AMBOS", "Ambos"),
                ],
                default="EN_PEDIDO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryconfig",
            name="modo",
            field=models.CharField(
                choices=[
                    ("PROPIO", "Propio"),
                    ("TERCERIZADO", "Tercerizado"),
                    ("AMBOS", "Ambos (propio + tercerizado)"),
                ],
                default="PROPIO",
                max_length=12,
            ),
        ),
    ]
