# Generated by Django 5.2.4 on 2026-08-27 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_add_employee_roles_and_collected_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("business_date", models.DateField()),
                (
                    "total_efectivo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_billeteras",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_tarjetas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_entregados", models.PositiveIntegerField(default=0)),
                ("total_rechazados", models.PositiveIntegerField(default=0)),
                ("ticket_payload", models.JSONField(blank=True, default=dict)),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closures_closed",
                        to="tenancy.employee",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_closures",
                        to="tenancy.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "business_date"],
                        name="closing_cas_merchan_8dd4f5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("merchant", "business_date"),
                        name="uniq_closure_per_merchant_date",
                    )
                ],
            },
        ),
    ]
