# Generated by Django 5.2.4 on 2026-09-10 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closing", "0001_add_cashclosure"),
        ("tenancy", "0007_passwordresettoken_sessionrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashclosure",
            name="closed_by_role",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cashclosure",
            name="closed_by_username",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="cashclosure",
            name="cashier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closures_closed",
                to="tenancy.employee",
            ),
        ),
    ]
