# Generated by Django 5.2.4 on 2026-09-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0007_passwordresettoken_sessionrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("phone", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=120)),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="tenancy.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "phone"],
                        name="customers_c_merchan_9b5368_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("merchant", "phone"),
                        name="uniq_customer_phone_per_merchant",
                    )
                ],
            },
        ),
    ]
