# Generated by Django 5.2.4 on 2026-08-27 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("tenancy", "0003_add_employee_roles_and_collected_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="collected_by_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collected_payments",
                to="tenancy.employee",
            ),
        ),
    ]
